#!/bin/bash

set -e

SCRIPT_PATH="$(dirname "$0")"

usage() { echo "Usage: $0 [-v]
    -v  Print version and exit
    -h  This help
" 1>&2; exit 1; } 

while getopts "v" o; do
    case "${o}" in
        v)  
            cat "$SCRIPT_PATH/version.txt"
            exit 0
            ;;
        *)
            usage
            ;;
    esac
done

if [ s"$GIT_PREFIX" != s ];then
    echo "run this from the root of your git repo"
    exit 1
fi

set +e # let's do some custom error handling here
FULLNAME="$(git config user.name)"
if [ s"$FULLNAME" = s ];then
    echo "This command requires a configured git."
    echo "git config --global user.name <YOURNAMEHERE>"
    echo "git config --global user.email <YOUREMAILHERE>"
    exit 4
fi
set -e
export FULLNAME
YEAR="$(date +%Y)"
export YEAR

gomplate --input-dir "$SCRIPT_PATH/template.tmpl" --output-dir .
