#!/bin/bash

set -e

SCRIPT_PATH="$(dirname "$0")"

usage() { echo "Usage: $0 [-v]
    -v  Print version and exit
    -h  This help
" 1>&2; exit 1; } 

while getopts "v" o; do
    case "${o}" in
        v)  
            cat "$SCRIPT_PATH/version.txt"
            exit 0
            ;;
        *)
            usage
            ;;
    esac
done

if [ s"$GIT_PREFIX" != s ];then
    echo "run this from the root of your git repo"
    exit 1
fi

FULLNAME="$(git config user.name)"
export FULLNAME
YEAR="$(date +%Y)"
export YEAR

gomplate --input-dir "$SCRIPT_PATH/template.tmpl" --output-dir .
