#!/bin/bash

SRC="$2"
DEST="${2#$1/}"

if [ -d "$2" ];then
  mkdir -p "$DEST"
else
  if [ -e "$DEST" ];then
    echo "Skipping $DEST which already exists" 1>&2
    exit 0
  fi
  gomplate < "$SRC" > "$DEST" || exit 1
  if [ -x "$SRC" ];then
    chmod +x "$DEST"
  fi
fi
